LAB ACTIVITY 13

Creating Numpy Arrays

array() method in numpy

In [7]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # Creating a 2-D Array
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Attributes of numpy: size, shape, ndim

In [8]:
#Displays the number of elements in a array
print(arr.size)

10


In [9]:
#Display the rows and columns
print(arr.shape) 

(2, 5)


In [10]:
#Displays the dimension of array
print(arr.ndim)

2


reshape() method in numpy

In [11]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)
print("Original shape:", arr.shape)

Original array: [1 2 3 4 5 6 7 8 9]
Original shape: (9,)


In [14]:
# Reshape to a 2D array
reshaped_arr = arr.reshape(3, 3)
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
New shape: (3, 3)


arange() method in numpy

In [15]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  #elemnt squaring
  b = np.arange(n) ** 3  
  c = a + b #element addign
  return c

numpysum(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [16]:
#array creation functions
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#to before 10 setp value 1
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
# 2 before 3 step value .1
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Array creation with different dimension using array() method from numpy module

In [20]:
#Creating Arrays from Sequences
a1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a1D)

[1 2 3 4 5 6 7 8 9]


In [22]:
#list of lists will create a 2D array
a2D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
#list of lists will create a 3D array
a3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(a3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


dtype attribute in numpy

In [26]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129])

In [27]:
#to be fixed
import numpy as np
np.array([127, 128, 129], dtype=np.int8)
# Error: OverflowError because the np.int8 data type cannot hold the values 128 and 129 (Here DeprecationWarning: based on python version)

C:\Users\jaish\AppData\Local\Temp\ipykernel_10736\3381874868.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)
C:\Users\jaish\AppData\Local\Temp\ipykernel_10736\3381874868.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

linspace() method in numpy

In [30]:
#The interval is divided into 5 equal steps
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

eye() method in numpy

In [31]:
#2D Array Creation functions 
#properties of special matrices represented as 2D arrays.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3, 5)   # Identity matrice of 3X5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [33]:
np.eye(3, 5, k=-2) 
# When k is negative (e.g., k=-2)
# when k is positive (e.g., k=1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [34]:
#Positive k argument
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

diag() method in numpy

In [35]:
#It returns an array containing the elements of the specified diagonal. 
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.
# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4
# Diagonal values are placed at positions: (0,1), (1,2), (2,3)
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [37]:
# numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
# It returns a 1D array that is only the diagonal elements. 

a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

Vandermonde Matrix

In [39]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
vandermonde_matrix = np.vander(x)
print(vandermonde_matrix)

[[       1        1        1        1        1        1        1        1
         1]
 [     256      128       64       32       16        8        4        2
         1]
 [    6561     2187      729      243       81       27        9        3
         1]
 [   65536    16384     4096     1024      256       64       16        4
         1]
 [  390625    78125    15625     3125      625      125       25        5
         1]
 [ 1679616   279936    46656     7776     1296      216       36        6
         1]
 [ 5764801   823543   117649    16807     2401      343       49        7
         1]
 [16777216  2097152   262144    32768     4096      512       64        8
         1]
 [43046721  4782969   531441    59049     6561      729       81        9
         1]]


In [40]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
vandermonde_matrix = np.vander(x)
print(vandermonde_matrix)

[[       1        1        1        1        1        1        1        1
         1]
 [     256      128       64       32       16        8        4        2
         1]
 [    6561     2187      729      243       81       27        9        3
         1]
 [   65536    16384     4096     1024      256       64       16        4
         1]
 [  390625    78125    15625     3125      625      125       25        5
         1]
 [ 1679616   279936    46656     7776     1296      216       36        6
         1]
 [ 5764801   823543   117649    16807     2401      343       49        7
         1]
 [16777216  2097152   262144    32768     4096      512       64        8
         1]
 [43046721  4782969   531441    59049     6561      729       81        9
         1]]


ones() method in numpy

In [42]:
#Creating a 1D array of size 5 filled with ones
arr1 = np.ones(5)  
print("1D Array of Ones:", arr1)

1D Array of Ones: [1. 1. 1. 1. 1.]


In [43]:
#Creating a 2D array filled with ones
arr2 = np.ones((3, 4))  
print("\n2D Array (3x4) of Ones:\n", arr2)


2D Array (3x4) of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
#Specifying data type as integer
arr3 = np.ones((2, 3), dtype=int)  # shape=(2,3), dtype=int
print("\n2D Integer Array (2x3) of Ones:\n", arr3)


2D Integer Array (2x3) of Ones:
 [[1 1 1]
 [1 1 1]]


In [45]:
#Creating a 3D array filled with ones
arr4 = np.ones((2, 2, 3)) 
print("\n3D Array of Ones:\n", arr4)


3D Array of Ones:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [46]:
#Creating a boolean array 
arr5 = np.ones((3, 3), dtype=bool)
print("\nBoolean Array (3x3) of Ones (True values):\n", arr5)


Boolean Array (3x3) of Ones (True values):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


zeros() method in numpy

In [47]:
#Creating a 1D array of size 5 filled with zeros
arr1 = np.zeros(5) 
print("1D Array of Zeros:", arr1)

1D Array of Zeros: [0. 0. 0. 0. 0.]


In [48]:
#Creating a 2D array filled with zeros
arr2 = np.zeros((3, 4))  
print("\n2D Array (3x4) of Zeros:\n", arr2)


2D Array (3x4) of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
#Specifying data type as integer
arr3 = np.zeros((2, 3), dtype=int)  
print("\n2D Integer Array (2x3) of Zeros:\n", arr3)


2D Integer Array (2x3) of Zeros:
 [[0 0 0]
 [0 0 0]]


In [50]:
#Creating a 3D array filled with zeros
arr4 = np.zeros((2, 2, 3))  
print("\n3D Array of Zeros:\n", arr4)


3D Array of Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [51]:
#Creating a boolean array 
arr5 = np.zeros((3, 3), dtype=bool)
print("\nBoolean Array (3x3) of Zeros (False values):\n", arr5)


Boolean Array (3x3) of Zeros (False values):
 [[False False False]
 [False False False]
 [False False False]]


indices() method in numpy

In [52]:
#Creating indices for a 2D array of shape (3, 3)
indices_2d = np.indices((3, 3))  
print("Indices for a 3x3 grid:\n", indices_2d)

Indices for a 3x3 grid:
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [53]:
#Row positions
print("\nRow indices (first array):\n", indices_2d[0])


Row indices (first array):
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


In [54]:
#Column positions
print("\nColumn indices (second array):\n", indices_2d[1]) 


Column indices (second array):
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


In [56]:
#Creating indices for a 2x4 array
indices_2x4 = np.indices((2, 4))

print("\nIndices for a 2x4 grid:\n", indices_2x4)


Indices for a 2x4 grid:
 [[[0 0 0 0]
  [1 1 1 1]]

 [[0 1 2 3]
  [0 1 2 3]]]


In [57]:
print("\nRow indices:\n", indices_2x4[0])


Row indices:
 [[0 0 0 0]
 [1 1 1 1]]


In [59]:
print("\nColumn indices:\n", indices_2x4[1])


Column indices:
 [[0 1 2 3]
 [0 1 2 3]]


random() method from random under numpy module

In [60]:
#Generate a single random float between 0 and 1
random_float = np.random.random()
print("Random Float (0 to 1):", random_float)

Random Float (0 to 1): 0.02953540122446585


In [61]:
#Generate a 1D array of 5 random floats between 0 and 1
random_array = np.random.random(5)
print("\n1D Array of Random Floats:", random_array)


1D Array of Random Floats: [0.57571188 0.62281919 0.96355738 0.74223058 0.27298365]


In [62]:
#Generate a 2D array of random floats between 0 and 1
random_matrix = np.random.random((3, 3))
print("\n2D Array (3x3) of Random Floats:\n", random_matrix)


2D Array (3x3) of Random Floats:
 [[0.0442001  0.3986138  0.83757372]
 [0.5673033  0.434625   0.07313124]
 [0.11030209 0.81609904 0.56503442]]


Indexing and Slicing

In [63]:
#Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("1D Array:", arr1d)

1D Array: [ 10  20  30  40  50  60  70  80  90 100]


In [64]:
print("\nIndexing on 1D Array:")
print("Element at index 0:", arr1d[0])   # First element
print("Element at index -1:", arr1d[-1]) # Last element


Indexing on 1D Array:
Element at index 0: 10
Element at index -1: 100


In [65]:
print("\nSlicing on 1D Array:")
print("Elements from index 1 to 4:", arr1d[1:5])  # From index 1 up to 4
print("Every second element:", arr1d[::2])        # Step of 2
print("Reverse array:", arr1d[::-1])  


Slicing on 1D Array:
Elements from index 1 to 4: [20 30 40 50]
Every second element: [10 30 50 70 90]
Reverse array: [100  90  80  70  60  50  40  30  20  10]


In [ ]:
#Jaishwanth A, 21MID0149